# Generated by Django 2.0.10 on 2019-01-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20190121_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date published',
            new_name='pub_date',
        ),
    ]
