# Generated by Django 2.0.10 on 2019-01-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20190121_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pub_date',
            new_name='date published',
        ),
    ]
