# Generated by Django 2.0.10 on 2019-01-23 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_auto_20190121_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('create_a_task', 'Can create task'), ('delete_a_task', 'Can delete task'), ('change_a_task', 'Can change task'), ('change_category', 'Can change category of task'))},
        ),
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
