# Generated by Django 2.0.10 on 2019-01-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_auto_20190123_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('create_a_task', 'Can create a new task'), ('delete_a_task', 'Can delete task'), ('change_a_task', 'Can change task'), ('change_category', 'Can change category of task'))},
        ),
    ]
