# Generated by Django 2.0.10 on 2019-01-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0012_auto_20190124_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date published',
            new_name='date_published',
        ),
    ]
