# Generated by Django 2.1.5 on 2019-01-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190118_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
